import type { Metadata } from "next";
import { spaceGrotesk, rwDewiAlt } from "./ui/fonts";
import "./ui/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} ${rwDewiAlt.variable} antialiased min-h-dvh flex flex-col`}
      >
        <main className="flex-1">{children}</main>
      </body>
    </html>
  );
}
